name: Master_CI
on:
  push:
    branches:
      - master

jobs:
  test:
    name: Run Unit Test
    runs-on: ubuntu-latest
    steps:
      - name: Check-out repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run test with pytest
        run: pytest

  deploy:
    name: Build And Deploy
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Check-out repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Install Dependencies
        run: |
          sudo npm install -g aws-cdk
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: CDK Deploy
        run: |
          cdk bootstrap
          cdk deploy --require-approval never
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_ACCOUNT_REGION }}
